In [4]:
#TO-DO Task
#Problem1
import numpy as np
import time
empti = np.empty((2, 2))
print("Empty array with size 2x2:\n", empti)

once = np.ones((4, 2))
print("One array with size 4x2:\n", once)

filled = np.full((4, 4), 5)
print("Filled array (4x4) with 5:\n", filled)

given = np.array([[1.5, 2.5], [3.5, 4.5]])
zeros_like_given = np.zeros_like(given)
print("Zeros like given:\n", zeros_like_given)

once_like_given = np.ones_like(given)
print("Ones like given:\n", once_like_given)

new_list = [1, 2, 3, 4]
converted = np.array(new_list)
print("Converted list to np array:", converted)

Empty array with size 2x2:
 [[3.60766909e-315 0.00000000e+000]
 [4.94065646e-324             nan]]
One array with size 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled array (4x4) with 5:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Zeros like given:
 [[0. 0.]
 [0. 0.]]
Ones like given:
 [[1. 1.]
 [1. 1.]]
Converted list to np array: [1 2 3 4]


In [5]:
#Problem2
import random as random
arr = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", arr)

arr=np.arange(0,9)
reshape_arr=arr.reshape(3,3)
print("\n3X3 matrix with values ranging from 0 to 8:\n", reshape_arr)

identity = np.eye(3)
print("\n3X3 identity matrix:\n", identity)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:", random_array)
print("Mean value of the array:", mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10X10 array with random values:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array of size 10 with replaced 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:", reversed_arr)

n,m = 5, 5
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print("\n2D array with 1 on border and 0 inside:\n", arr)

checkerboard = np.ones((8, 8))
checkerboard[1::2, ::2] = 0
checkerboard[::2, 1::2] = 0
print("\n8X8 matrix filled with checkerboard pattern:\n", checkerboard)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3X3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30: [0.53808413 0.19337924 0.92413342 0.01739873 0.51254857 0.78507552
 0.6049448  0.27878904 0.78705861 0.93915718 0.07122054 0.27840547
 0.54965379 0.57278205 0.53781902 0.73861835 0.74698444 0.3078081
 0.3292695  0.30132062 0.02358197 0.99091447 0.10822662 0.7889532
 0.89443005 0.87080252 0.11335647 0.68169955 0.84352034 0.22972126]
Mean value of the array: 0.5186552528458614

10X10 array with random values:
 [[0.75288416 0.23991842 0.69622214 0.2137964  0.96926501 0.85527269
  0.92933314 0.7869106  0.23575618 0.99363358]
 [0.91041697 0.60133424 0.4887423  0.29341825 0.8028019  0.13962122
  0.43439439 0.99040301 0.59865357 0.12209713]
 [0.32019153 0.46019538 0.6559530

In [6]:
#Problem3
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*2)
print((v,w)*5)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))#row concatenation
#v anw w reshape
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))#column concatenation
print(np.concatenate((x,v), axis =1))

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
(array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]))
(array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]))
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
[[ 1  2  9]
 [ 3  5 10]]


In [7]:
#Problem4
A = np.array([[3, 4], [7, 8]])

B = np.array([[5, 3], [2, 1]])

A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))

print(np.dot(A,B))
print(np.dot(B,A))

AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[36 13]
 [44 16]]


In [8]:
#Linear equation
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

[ 2.  1. -2.]


In [9]:
import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))


In [14]:
from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.07 s per loop
Numpy addition: 0.13 s per loop


In [15]:
from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

Pure Python multiplication: 0.07 s per loop
Numpy multiplication: 0.13 s per loop


In [16]:
from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

Pure Python dot product: 0.11 s per loop
Numpy dot product: 0.25 s per loop


In [17]:
from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")

Pure Python matrix multiplication: 124.08 s per loop
Numpy matrix multiplication: 0.07 s per loop
